(() => {
"use strict";
const $=id=>document.getElementById(id);
const simCanvas=$("simCanvas"),thetaCanvas=$("thetaCanvas"),omegaCanvas=$("omegaCanvas");
const simCtx=simCanvas.getContext("2d"),thetaCtx=thetaCanvas.getContext("2d"),omegaCtx=omegaCanvas.getContext("2d");
const ui={startBtn:$("startBtn"),resetBtn:$("resetBtn"),csvBtn:$("csvBtn"),pngBtn:$("pngBtn"),pdfBtn:$("pdfBtn"),saveBtn:$("saveBtn"),loadBtn:$("loadBtn"),loadInput:$("loadInput"),timerOut:$("timerOut"),avgOut:$("avgOut"),errorOut:$("errorOut"),photogateToggle:$("photogateToggle"),lSlider:$("lSlider"),mSlider:$("mSlider"),aSlider:$("aSlider"),gSelect:$("gSelect"),dampingToggle:$("dampingToggle"),bSlider:$("bSlider"),vectorToggle:$("vectorToggle"),lOut:$("lOut"),mOut:$("mOut"),aOut:$("aOut"),bOut:$("bOut"),timeOut:$("timeOut"),thetaOut:$("thetaOut"),omegaOut:$("omegaOut"),tTheoryOut:$("tTheoryOut"),tMeasuredOut:$("tMeasuredOut"),cyclesOut:$("cyclesOut"),keOut:$("keOut"),peOut:$("peOut"),meOut:$("meOut"),dataBody:$("dataBody")};
const state={running:false,dragging:false,t:0,theta:degToRad(+ui.aSlider.value),omega:0,alpha:0,dt:1/120,accumulator:0,lastFrame:performance.now(),history:[],table:[],nextSample:0,lastCross:null,measuredPeriods:[],cycles:0,geom:null};
function degToRad(v){return v*Math.PI/180} function radToDeg(v){return v*180/Math.PI} function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function p(){return{L:+ui.lSlider.value,m:+ui.mSlider.value,g:+ui.gSelect.value,beta:ui.dampingToggle.checked?+ui.bSlider.value:0}}
function alpha(theta,omega){const q=p();return-(q.g/q.L)*Math.sin(theta)-2*q.beta*omega}
function energy(){const q=p(),ke=.5*q.m*Math.pow(q.L*state.omega,2),pe=q.m*q.g*q.L*(1-Math.cos(state.theta));return{ke,pe,me:ke+pe}}
function theoryPeriod(){const q=p();return 2*Math.PI*Math.sqrt(q.L/q.g)}
function rk4(){const h=state.dt,th=state.theta,om=state.omega,oldTheta=state.theta;
const k1t=om,k1o=alpha(th,om);const k2t=om+.5*h*k1o,k2o=alpha(th+.5*h*k1t,om+.5*h*k1o);
const k3t=om+.5*h*k2o,k3o=alpha(th+.5*h*k2t,om+.5*h*k2o);const k4t=om+h*k3o,k4o=alpha(th+h*k3t,om+h*k3o);
state.theta+=h/6*(k1t+2*k2t+2*k3t+k4t);state.omega+=h/6*(k1o+2*k2o+2*k3o+k4o);state.alpha=alpha(state.theta,state.omega);state.t+=h;
if(oldTheta<0&&state.theta>=0&&state.omega>0){if(state.lastCross!==null){const T=state.t-state.lastCross;if(T>.1&&T<20){state.measuredPeriods.push(T);if(state.measuredPeriods.length>10)state.measuredPeriods.shift();state.cycles++}}state.lastCross=state.t}
const e=energy();state.history.push({t:state.t,theta:state.theta,omega:state.omega,...e});while(state.history.length&&state.history[0].t<state.t-20)state.history.shift();
if(state.t>=state.nextSample){state.table.push({t:state.t,theta:radToDeg(state.theta),omega:state.omega,...e});if(state.table.length>300)state.table.shift();state.nextSample+=.25}}
function reset(){state.running=false;state.dragging=false;state.t=0;state.theta=degToRad(+ui.aSlider.value);state.omega=0;state.alpha=alpha(state.theta,0);state.accumulator=0;state.history=[];state.table=[];state.nextSample=0;state.lastCross=null;state.measuredPeriods=[];state.cycles=0;ui.startBtn.textContent="Iniciar";update();drawAll()}
function formatTimer(v){const m=Math.floor(v/60),s=v-m*60,ss=Math.floor(s),ms=Math.floor((s-ss)*1000);return `${String(m).padStart(2,"0")}:${String(ss).padStart(2,"0")}.${String(ms).padStart(3,"0")}`}
function update(){const q=p(),e=energy();ui.lOut.textContent=q.L.toFixed(2)+" m";ui.mOut.textContent=q.m.toFixed(2)+" kg";ui.aOut.textContent=(+ui.aSlider.value).toFixed(0)+"°";ui.bOut.textContent=(+ui.bSlider.value).toFixed(2)+" s⁻¹";ui.timeOut.textContent=state.t.toFixed(2)+" s";ui.thetaOut.textContent=radToDeg(state.theta).toFixed(2)+"°";ui.omegaOut.textContent=state.omega.toFixed(3)+" rad/s";ui.tTheoryOut.textContent=theoryPeriod().toFixed(3)+" s";ui.tMeasuredOut.textContent=state.measuredPeriods.length?state.measuredPeriods[state.measuredPeriods.length-1].toFixed(3)+" s":"—";ui.cyclesOut.textContent=String(state.cycles);const avg=state.measuredPeriods.length?state.measuredPeriods.reduce((a,b)=>a+b,0)/state.measuredPeriods.length:null;ui.avgOut.textContent=avg?avg.toFixed(3)+" s":"—";ui.errorOut.textContent=avg?(Math.abs(avg-theoryPeriod())/theoryPeriod()*100).toFixed(2)+" %":"—";ui.timerOut.textContent=formatTimer(state.t);ui.keOut.textContent=e.ke.toFixed(4)+" J";ui.peOut.textContent=e.pe.toFixed(4)+" J";ui.meOut.textContent=e.me.toFixed(4)+" J";renderTable()}
function fit(canvas){const rect=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;canvas.width=Math.max(2,Math.floor(rect.width*dpr));canvas.height=Math.max(2,Math.floor(rect.height*dpr));const c=canvas.getContext("2d");c.setTransform(dpr,0,0,dpr,0,0);return{w:rect.width,h:rect.height}}
function drawSimulation(){const{w,h}=fit(simCanvas);simCtx.clearRect(0,0,w,h);const q=p(),pivot={x:w*.53,y:65},scale=Math.min(230,(h-140)/2),rope=q.L*scale,bob={x:pivot.x+rope*Math.sin(state.theta),y:pivot.y+rope*Math.cos(state.theta)},r=clamp(14+Math.sqrt(q.m)*9,14,27);
simCtx.strokeStyle="rgba(255,255,255,.35)";simCtx.lineWidth=6;simCtx.beginPath();simCtx.moveTo(pivot.x-95,pivot.y-20);simCtx.lineTo(pivot.x+95,pivot.y-20);simCtx.stroke();
simCtx.setLineDash([6,6]);simCtx.strokeStyle="rgba(255,255,255,.25)";simCtx.lineWidth=1.5;simCtx.beginPath();simCtx.moveTo(pivot.x,pivot.y);simCtx.lineTo(pivot.x,pivot.y+rope+20);simCtx.stroke();simCtx.setLineDash([]);
simCtx.strokeStyle="#f2f8ff";simCtx.lineWidth=3;simCtx.beginPath();simCtx.moveTo(pivot.x,pivot.y);simCtx.lineTo(bob.x,bob.y);simCtx.stroke();
simCtx.fillStyle="#27d48a";simCtx.beginPath();simCtx.arc(pivot.x,pivot.y,6,0,Math.PI*2);simCtx.fill();
const grad=simCtx.createRadialGradient(bob.x-r*.3,bob.y-r*.35,r*.2,bob.x,bob.y,r);grad.addColorStop(0,"#8ff7c8");grad.addColorStop(.5,"#27d48a");grad.addColorStop(1,"#087247");simCtx.fillStyle=grad;simCtx.strokeStyle="#afffde";simCtx.lineWidth=2;simCtx.beginPath();simCtx.arc(bob.x,bob.y,r,0,Math.PI*2);simCtx.fill();simCtx.stroke();
if(ui.vectorToggle.checked){drawArrow(bob.x,bob.y,bob.x,bob.y+55,"#ff8a5b","Peso");const ux=(pivot.x-bob.x)/rope,uy=(pivot.y-bob.y)/rope;drawArrow(bob.x,bob.y,bob.x+ux*65,bob.y+uy*65,"#3bbcf0","T")}
simCtx.fillStyle="#eaf7ff";simCtx.font="12px system-ui";simCtx.fillText("θ = "+radToDeg(state.theta).toFixed(1)+"°",14,24);simCtx.fillText("t = "+state.t.toFixed(2)+" s",14,43);state.geom={pivot,bob,r}}
function drawArrow(x1,y1,x2,y2,color,label){const a=Math.atan2(y2-y1,x2-x1),head=9;simCtx.strokeStyle=color;simCtx.fillStyle=color;simCtx.lineWidth=2.2;simCtx.beginPath();simCtx.moveTo(x1,y1);simCtx.lineTo(x2,y2);simCtx.stroke();simCtx.beginPath();simCtx.moveTo(x2,y2);simCtx.lineTo(x2-head*Math.cos(a-Math.PI/6),y2-head*Math.sin(a-Math.PI/6));simCtx.lineTo(x2-head*Math.cos(a+Math.PI/6),y2-head*Math.sin(a+Math.PI/6));simCtx.closePath();simCtx.fill();simCtx.font="11px system-ui";simCtx.fillText(label,x2+4,y2-4)}
function drawSeries(canvas,ctx,points,label,color){const{w,h}=fit(canvas);ctx.clearRect(0,0,w,h);const m={l:44,r:14,t:14,b:28};ctx.strokeStyle="rgba(255,255,255,.15)";ctx.strokeRect(m.l,m.t,w-m.l-m.r,h-m.t-m.b);ctx.fillStyle="rgba(255,255,255,.75)";ctx.font="11px system-ui";ctx.fillText(label,8,16);if(points.length<2)return;const xmin=points[0].x,xmax=Math.max(points[points.length-1].x,xmin+1);let ymin=Math.min(...points.map(p=>p.y)),ymax=Math.max(...points.map(p=>p.y));if(Math.abs(ymax-ymin)<1e-8){ymin-=1;ymax+=1}const pad=(ymax-ymin)*.1;ymin-=pad;ymax+=pad;const X=x=>m.l+(x-xmin)/(xmax-xmin)*(w-m.l-m.r),Y=y=>m.t+(1-(y-ymin)/(ymax-ymin))*(h-m.t-m.b);ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(X(p.x),Y(p.y)):ctx.moveTo(X(p.x),Y(p.y)));ctx.stroke()}
function drawAll(){drawSimulation();drawSeries(thetaCanvas,thetaCtx,state.history.map(p=>({x:p.t,y:radToDeg(p.theta)})),"θ (°)","#3bbcf0");drawSeries(omegaCanvas,omegaCtx,state.history.map(p=>({x:p.t,y:p.omega})),"ω (rad/s)","#ffcb59")}
function renderTable(){ui.dataBody.innerHTML=state.table.slice(-60).map(r=>`<tr><td>${r.t.toFixed(2)}</td><td>${r.theta.toFixed(2)}</td><td>${r.omega.toFixed(3)}</td><td>${r.ke.toFixed(4)}</td><td>${r.pe.toFixed(4)}</td><td>${r.me.toFixed(4)}</td></tr>`).join("")}
function exportCsv(){const header="t_s,theta_deg,omega_rad_s,Ec_J,Ep_J,Em_J",rows=state.table.map(r=>[r.t.toFixed(4),r.theta.toFixed(6),r.omega.toFixed(6),r.ke.toFixed(8),r.pe.toFixed(8),r.me.toFixed(8)].join(",")),blob=new Blob([[header,...rows].join("\n")],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="datos_pendulo.csv";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
function pointer(event){const r=simCanvas.getBoundingClientRect();return{x:event.clientX-r.left,y:event.clientY-r.top}}

function download(name,blob){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),800)}
function capturePng(){drawAll();simCanvas.toBlob(blob=>blob&&download("pendulo_captura.png",blob),"image/png")}
function savePractice(){const data={version:"2.0",controls:{L:ui.lSlider.value,m:ui.mSlider.value,a:ui.aSlider.value,g:ui.gSelect.value,b:ui.bSlider.value,damping:ui.dampingToggle.checked,vectors:ui.vectorToggle.checked,photogate:ui.photogateToggle.checked},table:state.table};download("practica_pendulo.json",new Blob([JSON.stringify(data,null,2)],{type:"application/json"}))}
function loadPractice(file){const reader=new FileReader();reader.onload=()=>{try{const d=JSON.parse(reader.result),c=d.controls||{};if(c.L)ui.lSlider.value=c.L;if(c.m)ui.mSlider.value=c.m;if(c.a)ui.aSlider.value=c.a;if(c.g)ui.gSelect.value=c.g;if(c.b)ui.bSlider.value=c.b;ui.dampingToggle.checked=!!c.damping;ui.vectorToggle.checked=c.vectors!==false;ui.photogateToggle.checked=c.photogate!==false;reset();if(Array.isArray(d.table)){state.table=d.table;renderTable()}alert("Práctica cargada.")}catch(e){alert("Archivo JSON no válido.")}};reader.readAsText(file)}
function bind(){ui.startBtn.onclick=()=>{state.running=!state.running;ui.startBtn.textContent=state.running?"Pausar":"Iniciar"};ui.resetBtn.onclick=reset;ui.csvBtn.onclick=exportCsv;ui.pngBtn.onclick=capturePng;ui.pdfBtn.onclick=()=>{update();drawAll();setTimeout(()=>window.print(),120)};ui.saveBtn.onclick=savePractice;ui.loadBtn.onclick=()=>ui.loadInput.click();ui.loadInput.onchange=e=>{const f=e.target.files[0];if(f)loadPractice(f)};[ui.lSlider,ui.mSlider,ui.aSlider,ui.bSlider].forEach(el=>{el.addEventListener("input",()=>{if(el===ui.aSlider){state.theta=degToRad(+ui.aSlider.value);state.omega=0}update();drawAll()});el.addEventListener("change",reset)});[ui.gSelect,ui.dampingToggle,ui.photogateToggle].forEach(el=>el.addEventListener("change",reset));ui.vectorToggle.addEventListener("change",drawSimulation);
simCanvas.addEventListener("pointerdown",e=>{const pos=pointer(e),g=state.geom;if(!g||Math.hypot(pos.x-g.bob.x,pos.y-g.bob.y)>g.r+12)return;state.dragging=true;state.running=false;ui.startBtn.textContent="Iniciar";simCanvas.setPointerCapture(e.pointerId)});
simCanvas.addEventListener("pointermove",e=>{if(!state.dragging||!state.geom)return;const pos=pointer(e),pv=state.geom.pivot;state.theta=clamp(Math.atan2(pos.x-pv.x,pos.y-pv.y),degToRad(-80),degToRad(80));state.omega=0;ui.aSlider.value=String(clamp(Math.round(Math.abs(radToDeg(state.theta))),1,70));update();drawAll()});
simCanvas.addEventListener("pointerup",e=>{state.dragging=false;if(simCanvas.hasPointerCapture(e.pointerId))simCanvas.releasePointerCapture(e.pointerId);reset()});document.querySelectorAll(".checkQuiz").forEach(btn=>btn.onclick=()=>{const art=btn.closest("article"),chosen=art.querySelector("input:checked"),out=art.querySelector("small");if(!chosen){out.textContent="Selecciona una respuesta.";return}out.textContent=chosen.value===art.dataset.answer?"Correcto.":"Revisa el comportamiento físico y vuelve a intentar."});addEventListener("resize",drawAll)}
function loop(now){const delta=Math.min((now-state.lastFrame)/1000,.05);state.lastFrame=now;if(state.running&&!state.dragging){state.accumulator+=delta;while(state.accumulator>=state.dt){rk4();state.accumulator-=state.dt}update()}drawAll();requestAnimationFrame(loop)}
bind();reset();if("serviceWorker" in navigator&&location.protocol.startsWith("http"))navigator.serviceWorker.register("sw.js").catch(()=>{});requestAnimationFrame(loop);
})();